/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a fbddbus.h:fbddbus.cpp fbddbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "fbddbus.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FusionbrainAdaptor
 */

FusionbrainAdaptor::FusionbrainAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FusionbrainAdaptor::~FusionbrainAdaptor()
{
    // destructor
}

double FusionbrainAdaptor::GetAnalogValue(int ionum, int samplenum)
{
    // handle method call org.openice.fbd.fusionbrain.GetAnalogValue
    double value;
    QMetaObject::invokeMethod(parent(), "GetAnalogValue", Q_RETURN_ARG(double, value), Q_ARG(int, ionum), Q_ARG(int, samplenum));
    return value;
}

void FusionbrainAdaptor::SetAllOutput(int low, int high)
{
    // handle method call org.openice.fbd.fusionbrain.SetAllOutput
    QMetaObject::invokeMethod(parent(), "SetAllOutput", Q_ARG(int, low), Q_ARG(int, high));
}

void FusionbrainAdaptor::SetSingleOutput(int ionum, bool active)
{
    // handle method call org.openice.fbd.fusionbrain.SetSingleOutput
    QMetaObject::invokeMethod(parent(), "SetSingleOutput", Q_ARG(int, ionum), Q_ARG(bool, active));
}

