/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a fbddbus.h:fbddbus.cpp fbddbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FBDDBUS_H_1246206074
#define FBDDBUS_H_1246206074

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.openice.fbd.fusionbrain
 */
class FusionbrainAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.openice.fbd.fusionbrain")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.openice.fbd.fusionbrain\" >\n"
"    <method name=\"SetSingleOutput\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"ionum\" />\n"
"      <arg direction=\"in\" type=\"b\" name=\"active\" />\n"
"    </method>\n"
"    <method name=\"SetAllOutput\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"low\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"high\" />\n"
"    </method>\n"
"    <method name=\"GetAnalogValue\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"ionum\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"samplenum\" />\n"
"      <arg direction=\"out\" type=\"d\" name=\"value\" />\n"
"    </method>\n"
"    <signal name=\"AnalogValueChanged\" >\n"
"      <arg direction=\"out\" type=\"i\" name=\"analognum\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"value\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    FusionbrainAdaptor(QObject *parent);
    virtual ~FusionbrainAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double GetAnalogValue(int ionum, int samplenum);
    void SetAllOutput(int low, int high);
    void SetSingleOutput(int ionum, bool active);
Q_SIGNALS: // SIGNALS
    void AnalogValueChanged(int analognum, int value);
};

#endif
